# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_auto_20171124_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('cards', models.ManyToManyField(to='cards.Card')),
            ],
        ),
    ]
