# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('gold', models.IntegerField()),
                ('str', models.IntegerField(blank=True, default=0)),
                ('initiative', models.IntegerField(blank=True, default=0)),
                ('claim', models.IntegerField(blank=True, default=0)),
                ('reserve', models.IntegerField(blank=True, default=0)),
                ('image_url', models.URLField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='challenges',
            field=models.ManyToManyField(blank=True, to='cards.Challenge'),
        ),
        migrations.AddField(
            model_name='card',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Faction'),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Set'),
        ),
        migrations.AddField(
            model_name='card',
            name='traits',
            field=models.ManyToManyField(blank=True, to='cards.Trait'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Type'),
        ),
    ]
